const usuarios = [
    "user1",
    "username",
    "user_name",
    "user-name",
    "user123",
    "test_user",
    "john_doe",
    "alice-123",
    "bob_the_builder",
    "user-456",
    "admin_user",
    "guest_user",
    "sample_user",
    "user001",
    "test_user_01",
    "valid_username",
    "my_user-001",
    "test-username",
    "a_b_c",
    "abc_def_123",
    "example-name",
    "username123",
    "user-12345",
    "user_01",
    "validUser",
    "my_username",
    "user01",
    "first_last",
    "short1",
    "test-user",
    "usernameValid",
    "simple_user",
    "user_00123",
    "user_test_123",
    "my-user_name",
    "test1",
    "valid_1_user",
    "user1-2",
    "x-y-z",
    "12345",
    "valid_user1",
    "user-9",
    "name_user",
    "user2",
    "user3",
    "user4",
    "user5",
    "user6",
    "user7",
    "user8",
    "user9",
    "user10",
    "user11",
    "user12",
    "user13",
    "user14",
    "user15",
    "user16",
    "user17",
    "user18",
    "user19",
    "user20",
    "validuser_21",
    "username-22",
    "user23",
    "test_user24",
    "anotherUser25",
    "user-name-26",
    "username-27",
    "us28",
    "user-name-29",
    "user30",
    "name31",
    "user_name32",
    "username33",
    "user34",
    "name_35",
    "username-36",
    "user37",
    "us38",
    "username39",
    "username40",
    "user41",
    "user_name42",
    "username-43",
    "name44",
    "name_45",
    "name46",
    "test-username-47",
    "user48",
    "username49",
    "u50",
    "user51",
    "username_52",
    "test_user53",
    "valid_user54",
    "user55",
    "username-56",
    "name57",
    "user_name58",
    "user59",
    "user60",
    "user_name61",
    "user62",
    "user63",
    "user-name64",
    "user65",
    "user66",
    "user67",
    "user68",
    "user69",
    "user70",
    "user71",
    "user72",
    "user73",
    "user74",
    "user75",
    "user76",
    "user77",
    "user78",
    "user79",
    "user80",
    "user81",
    "user82",
    "user83",
    "user84",
    "user85",
    "user86",
    "user87",
    "user88",
    "user89",
    "user90",
    "user91",
    "user92",
    "user93",
    "user94",
    "user95",
    "user96",
    "user97",
    "user98",
    "user99",
    "user100",
    "invalid user",       // Inválido (contém espaço)
    "us",                 // Inválido (menos de 3 caracteres)
    "username1234567890",// Inválido (mais de 16 caracteres)
    "user@name",          // Inválido (caractere especial)
    "user!name",          // Inválido (caractere especial)
    "user name",          // Inválido (contém espaço)
    "us1-",               // Inválido (menos de 3 caracteres)
    "-user",              // Inválido (começa com hífen)
    "user-",              // Inválido (termina com hífen)
    "12345678901234567",  // Inválido (mais de 16 caracteres)
    "u",                  // Inválido (menos de 3 caracteres)
    "a-b-c-d-e-f-g-h-i", // Inválido (mais de 16 caracteres)
    "user$name",          // Inválido (caractere especial)
  ];
  const isUser = /^[a-zA-Z0-9_-]{3,16}$/; 
  
  usuarios.forEach(user => {
    if(isUser.test(user)) {
        console.log('Seja bem vindo '+ user);
    }
  })